### ISSUE TITLE
Expand a compact document

### ISSUE THREAD

**Issue by pdf** [kazarena/json-gold#5]
Maybe I'm doing something wrong, but given the following trivial example describing a compact document, attempting to expand it:

``` go
package main

import "github.com/kazarena/json-gold/ld"

func main() {
        proc := ld.NewJsonLdProcessor()
        options := ld.NewJsonLdOptions(``)

        /*
                {
                        "@context": "http://schema.org/",
                        "@type": "Person",
                        "name": "Jane Doe",
                        "jobTitle": "Professor",
                        "telephone": "(425) 123-4567",
                        "url": "http://www.janedoe.com"
                }
        */
        doc := make(map[string]interface{})
        doc[`@context`] = `http://schema.org/`
        doc[`@type`] = `Person`
        doc[`name`] = `Jane Doe`
        doc[`jobTitle`] = `Professor`
        doc[`telephone`] = `(425) 123-4567`
        doc[`url`] = `http://www.janedoe.com`

        expanded, err := proc.Expand(doc, options)
        if err != nil {
                panic(err)
        }

        ld.PrintDocument("JSON-LD expansion succeeded", expanded)
}
```

I get the following result, where I expected it to succeed:

```
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
github.com/kazarena/json-gold/ld.(*Context).parse(0xc8200d9d80, 0x6d06c0, 0xc8200dd500, 0xc8200d4f70, 0x0, 0x0, 0x5, 0x0, 0x0)
        /storage/workspace/golang/src/github.com/kazarena/json-gold/ld/context.go:91 +0x15c4
github.com/kazarena/json-gold/ld.(*Context).Parse(0xc8200d9d80, 0x6d06c0, 0xc8200dd500, 0x8, 0x0, 0x0)
        /storage/workspace/golang/src/github.com/kazarena/json-gold/ld/context.go:61 +0x7a
github.com/kazarena/json-gold/ld.(*JsonLdApi).Expand(0xc8200d5c37, 0xc8200d9d80, 0x0, 0x0, 0x6ceec0, 0xc82000fbf0, 0x0, 0x0, 0x0, 0x0)
        /storage/workspace/golang/src/github.com/kazarena/json-gold/ld/api_expand.go:61 +0x1d7
github.com/kazarena/json-gold/ld.(*JsonLdProcessor).expand(0xc8200d5e50, 0x6ceec0, 0xc82000fbf0, 0xc820086b00, 0x0, 0x0, 0x0, 0x0, 0x0)
        /storage/workspace/golang/src/github.com/kazarena/json-gold/ld/processor.go:141 +0x6d7
github.com/kazarena/json-gold/ld.(*JsonLdProcessor).Expand(0xc8200d5e50, 0x6ceec0, 0xc82000fbf0, 0xc820086b00, 0x0, 0x0, 0x0, 0x0, 0x0)
        /storage/workspace/golang/src/github.com/kazarena/json-gold/ld/processor.go:79 +0x69
main.main()
        /storage/workspace/golang/src/ldtest/main.go:27 +0x612

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
exit status 2
```

**Comment by kazarena** [comment]
Hi @pdf,
Good question, your code should have worked. I'm using schema.org all the time in a very similar fashion.

I think I know what's going on. Expect a fix some time today.

**Comment by kazarena** [comment]
This issue has been resolved. It was manifesting itself when one processes an in-memory document with remote context and default options (@base set to ""). I still need to review the logic behind an empty @base - not 100% happy with the current implementation inherited from other libraries. I also added your code into examples for Expand operation as it's very useful.

Thank you for reporting it!

**Comment by pdf** [comment]
Great, thanks for the lib and for the fast turn-around on this @kazarena,
